name: Archive
inputs:
  scheme:
    description: Scheme
    required: true
  destination:
    description: Destination
    required: true
  app-store-key:
    description: App Store key in PEM PKCS#8 format
    required: true
  app-store-key-id:
    description: App Store key ID
    required: true
  app-store-key-issuer-id:
    description: App Store key issuer ID
    required: true
  archive-path:
    description: Xcode archive path
    required: true
runs:
  using: composite
  steps:
  - shell: bash
    working-directory: Apple
    run: |
      echo "${{ inputs.app-store-key }}" > AuthKey_${{ inputs.app-store-key-id }}.p8

      xcodebuild archive \
        -allowProvisioningUpdates \
        -allowProvisioningDeviceRegistration \
        -skipPackagePluginValidation \
        -skipMacroValidation \
        -onlyUsePackageVersionsFromResolvedFile \
        -authenticationKeyID ${{ inputs.app-store-key-id }} \
        -authenticationKeyIssuerID ${{ inputs.app-store-key-issuer-id }} \
        -authenticationKeyPath "${PWD}/AuthKey_${{ inputs.app-store-key-id }}.p8" \
        -onlyUsePackageVersionsFromResolvedFile \
        -scheme '${{ inputs.scheme }}' \
        -destination '${{ inputs.destination }}' \
        -archivePath '${{ inputs.archive-path }}' \
        -resultBundlePath BuildResults.xcresult

      ./Tools/xcresulttool-github BuildResults.xcresult
      
      rm -rf AuthKey_${{ inputs.app-store-key-id }}.p8
