name: Build RPM
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches:
    - "*"
jobs:
  build:
    name: Build RPM
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - name: Install RPM
      run: cargo install cargo-generate-rpm
    - name: Build RPM
      run: |
        cargo build --release
        strip -s target/release/burrow
    - name: Build RPM
      run: cargo generate-rpm -p burrow

