on:
  push:
    branches: [main]
  pull_request:
name: Build Flatpak
jobs:
  flatpak:
    name: Build Flatpak
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-45
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: Burrow.flatpak
        manifest-path: burrow-gtk/com.hackclub.burrow.devel.json
        cache-key: flatpak-builder-${{ github.sha }}
