name: Build Docker
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - "*"
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: arm64
    - name: Setup BuildKit
      uses: docker/setup-buildx-action@v2
    - name: Authenticate
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract Metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          type=sha
          type=match,pattern=builds/(.*),group=1
          type=raw,value=latest,enable={{is_default_branch}}
    - name: Build and Push
      uses: docker/build-push-action@v4
      with:
        platforms: ${{ github.event_name != 'pull_request' && 'linux/amd64,linux/arm64' || 'linux/amd64'  }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
